import type { RssSourceConfig } from "./rss-source.types";

export const rssSources: RssSourceConfig[] = [
  {
    id: "openai-news",
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "products", "business", "automation"],
    pollEveryMinutes: 30,
    contentMode: "auto",
  },
  {
    id: "google-ai",
    name: "Google AI",
    url: "https://blog.google/innovation-and-ai/technology/ai/rss/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "products", "productivity", "research"],
    pollEveryMinutes: 30,
    contentMode: "excerpt",
  },
  {
    id: "microsoft-ai",
    name: "Microsoft — AI",
    url: "https://news.microsoft.com/source/tag/ai/feed/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "copilot", "products", "business"],
    pollEveryMinutes: 30,
    contentMode: "excerpt",
  },
  {
    id: "nvidia-ai",
    name: "NVIDIA — AI",
    url: "https://blogs.nvidia.com/blog/category/generative-ai/feed/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "models", "hardware", "robotics", "open-source"],
    pollEveryMinutes: 30,
    contentMode: "full",
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    url: "https://deepmind.google/blog/rss.xml",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "research", "models", "science", "safety"],
    pollEveryMinutes: 60,
    contentMode: "excerpt",
  },
  {
    id: "cloudflare-ai",
    name: "Cloudflare — AI",
    url: "https://blog.cloudflare.com/tag/ai/rss/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "agents", "security", "infrastructure", "developers"],
    pollEveryMinutes: 30,
    contentMode: "full",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot Changelog",
    url: "https://github.blog/changelog/label/copilot/feed/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "coding", "developers", "agents", "products"],
    pollEveryMinutes: 30,
    contentMode: "full",
  },
  {
    id: "mozilla-ai",
    name: "Mozilla.ai",
    url: "https://blog.mozilla.ai/rss/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "open-source", "privacy", "developers", "agents"],
    pollEveryMinutes: 60,
    contentMode: "full",
  },
  {
    id: "zapier-blog",
    name: "Zapier Blog",
    url: "https://zapier.com/blog/feeds/latest/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["automation", "ai", "productivity", "small-business"],
    pollEveryMinutes: 60,
    contentMode: "auto",
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch — Artificial Intelligence",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "news", "startups", "business"],
    pollEveryMinutes: 30,
    contentMode: "auto",
  },
  {
    id: "venturebeat-ai",
    name: "VentureBeat — AI",
    url: "https://venturebeat.com/category/ai/feed/",
    enabled: true,
    language: "en",
    region: "global",
    tags: ["ai", "enterprise", "business", "technology"],
    pollEveryMinutes: 30,
    contentMode: "full",
  },
];
