import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from "drizzle-orm/pg-core";

/**
 * Identity tables managed through Better Auth (FEAT-AUTH-001).
 *
 * Better Auth's Drizzle adapter resolves models by the exported property name
 * (`users`, `sessions`, ... because the adapter runs with `usePlural`) and
 * columns by the property key, not by the SQL column name. Keep the property
 * keys equal to Better Auth's field names (`emailVerified`, `expiresAt`,
 * `ipAddress`, ...) and keep the SQL names snake_case like the rest of the
 * schema.
 *
 * Ids are opaque text generated by Better Auth, the same shape as
 * `workspaces.id`. Rows are written by the auth library and by the auth
 * module's own server code; route handlers never insert here directly.
 */

const timestampColumn = (name: string) =>
  timestamp(name, { withTimezone: true, mode: "date" });

const auditTimestamps = {
  createdAt: timestampColumn("created_at").defaultNow().notNull(),
  updatedAt: timestampColumn("updated_at").defaultNow().notNull(),
};

export const users = pgTable(
  "users",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    emailVerified: boolean("email_verified").default(false).notNull(),
    image: text("image"),
    ...auditTimestamps,
  },
  (table) => [
    unique("users_email_unique").on(table.email),
    // Google returns canonical lowercase emails; this guards any future
    // provider or manual insert from creating a second account by case.
    uniqueIndex("users_email_lower_unique_idx").on(sql`lower(${table.email})`),
  ],
);

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** Opaque session token carried by the cookie; never logged. */
    token: text("token").notNull(),
    expiresAt: timestampColumn("expires_at").notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    ...auditTimestamps,
  },
  (table) => [
    unique("sessions_token_unique").on(table.token),
    index("sessions_user_id_idx").on(table.userId),
  ],
);

/**
 * One authentication method linked to a user. During the alpha the only
 * provider is Google; `password` stays null until email sign-in exists.
 */
export const accounts = pgTable(
  "accounts",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestampColumn("access_token_expires_at"),
    refreshTokenExpiresAt: timestampColumn("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    ...auditTimestamps,
  },
  (table) => [
    unique("accounts_provider_account_unique").on(
      table.providerId,
      table.accountId,
    ),
    index("accounts_user_id_idx").on(table.userId),
  ],
);

/** Short-lived records Better Auth uses for OAuth state and future email flows. */
export const verifications = pgTable(
  "verifications",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestampColumn("expires_at").notNull(),
    ...auditTimestamps,
  },
  (table) => [index("verifications_identifier_idx").on(table.identifier)],
);

export type AuthUser = typeof users.$inferSelect;
export type AuthSession = typeof sessions.$inferSelect;
export type AuthAccount = typeof accounts.$inferSelect;
